### rdf
GET http://www.w3.org/1999/02/22-rdf-syntax-ns#
Accept: text/turtle

### rdfs
GET http://www.w3.org/2000/01/rdf-schema#
Accept: text/turtle

### owl
GET http://www.w3.org/2002/07/owl#
Accept: text/turtle

### dc
GET http://purl.org/dc/elements/1.1/
Accept: text/turtle

### dcam
GET http://purl.org/dc/dcam/
Accept: text/turtle

### dcterms
GET http://purl.org/dc/terms/
Accept: text/turtle

### skos
GET http://www.w3.org/2004/02/skos/core#
Accept: application/rdf+xml

### xsd 1.0
GET http://www.w3.org/2001/XMLSchema.xsd
Accept: application/xml

### xsd 1.1
GET https://www.w3.org/2009/XMLSchema/XMLSchema.xsd
Accept: application/xml

### xml
GET http://www.w3.org/2001/xml.xsd
Accept: application/xml

### grddl
GET http://www.w3.org/2003/g/data-view#
Accept: application/rdf+xml

### hfp
GET http://www.w3.org/2001/XMLSchema-hasFacetAndProperty.xsd
Accept: application/xml

### xhtml
GET http://www.w3.org/1999/xhtml
Accept: application/xml

### xsi
GET http://www.w3.org/2001/XMLSchema-instance
Accept: application/xml

### rddl-purposes
GET http://www.rddl.org/purposes#
Accept: application/rdf+xml

### rddl
GET http://www.rddl.org/
Accept: application/rdf+xml

### xlink
GET http://www.w3.org/1999/xlink
Accept: application/xml

### admin
GET https://web.resource.org/rss/1.0/modules/admin/
Accept: application/xml

### foaf
GET http://xmlns.com/foaf/0.1/
Accept: application/rdf+xml

### doap
GET http://usefulinc.com/ns/doap#
Accept: application/rdf+xml

### vs
GET http://www.w3.org/2003/06/sw-vocab-status/ns#
Accept: application/rdf+xml

### wot
GET http://xmlns.com/wot/0.1/
Accept: application/rdf+xml

### vann
GET https://vocab.org/vann/vann-vocab-20100607.rdf
Accept: application/rdf+xml

### wn20full
GET http://www.w3.org/2006/03/wn/wn20/schemas/wnfull.rdfs
Accept: application/rdf+xml

### wn20basic
GET http://www.w3.org/2006/03/wn/wn20/schemas/wnbasic.rdfs
Accept: application/rdf+xml

### wn20synset
GET http://www.w3.org/2006/03/wn/wn20/rdf/wordnet-synset.rdf
Accept: application/rdf+xml

### wn20schema
GET http://www.w3.org/2006/03/wn/wn20/schema/
Accept: application/rdf+xml

### wn20instances
GET http://www.w3.org/2006/03/wn/wn20/instances/
Accept: application/rdf+xml

### cc
GET https://web.resource.org/cc/schema.rdf
Accept: application/rdf+xml

### bio
GET https://vocab.org/bio/schema.rdf
Accept: application/rdf+xml

### ov
GET https://vocab.org/open/terms.rdf
Accept: application/rdf+xml

### label
GET http://liveschema.eu/dataset/d7eee29f-7421-4e7e-b515-ef2f5a7c31f3/resource/355f81b1-fb7a-4dae-94ec-fa018ca7139f/download/lov_label.ttl
Accept: text/turtle
